id: IDCFDDA11
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-05-30T22:10:11.597838'
last_modified: '2022-05-30T22:10:11.597850'
parser: null
source_metadata:
  title: Khenchen Namdrol Tsering Series
  language: en
  description: 'A series of texts and teachings by the learned khenpo Namdrol Tsering
    (mkhan chen rnam grol tshe ring, b. 1953):'
  volume:
    fBBF0:
      title: Commentary on the Madhyamakāvatāra—Part 1—Collection of Reasoning
      base_file: fBBF0.txt
      order: 1
      parent: Oral Teachings
    fE926:
      title: Commentary on the Madhyamakāvatāra—Part 2—Title and Translators Homage
      base_file: fE926.txt
      order: 2
      parent: Oral Teachings
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
